version: 2
registries:
  github-octocat:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.REPOSITORY_API_GITHUB_TOKEN}}
updates:
  - package-ecosystem: mix
    directory: "/"
    insecure-external-code-execution: allow
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    registries:
      - github-octocat

